# Commands to start on workspace startup
tasks:
  - init: |
      npm install -g heroku 
  - command: |
      cd src && pip install -r requirements.txt
# Ports to expose on workspace startup
ports:
  - port: 8500
    onOpen: open-browser